apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
spec:
  generators:
  - git:
      repoURL: https://github.com/Platform9-Community/p9-argocd-reference-arch.git
      revision: HEAD
      directories:
      - path: infrastructure/istio/1.17.2
      - path: kube-prometheus-stack/38.0.4
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Platform9-Community/p9-argocd-reference-arch.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
