apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-root
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: argocd-root
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Platform9-Community/p9-argocd-reference-arch.git
    targetRevision: HEAD
    path: clusters/nyc-prod/argocd
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
