apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infrastructure/argocd-system/v2.7.9
namespace: argocd
# example patch
#patches:
#  - path: ./argocd-redis-ha-server_patch.json
#    target:
#      group: apps
#      version: v1
#      kind: StatefulSet
#      name: argocd-redis-ha-server
